# -*- coding: utf-8 -*-
"""ConverorDeUnidades.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XTU9Y61e7uvMyEpaA1ITfEoFSQe2umBA
"""

print("-----Bienvenido a la calculadora de conversión de unidades-------")
print("Menu de Conversiones")
print("1.- Temperatura.- Celsius-Fahrenheit")
print("2.- Temperatura.- Fahrenheit-Celsius")
print("3.-Longitud.- Metros-Centímetros")
print("4.-Longitud.- Centímetros-Metros")
print("5.-Masa.-Gramos-Kilográmos")
print("6.-Masa.- Kilogramos-Gramos")
print("7.-Salir")

opcion = input("Opción (1-4):")

if opcion == "1":
  temCe = float(input("Temperatura (Celsius):"))
  temFa = (9/5)*(temCe)+32
  print(f"La Temperatura en Grados Fahrenheit es: {temFa:.2}")

if opcion == "2":
  temFa = float(input("Temperatura (Fahrenheit):"))
  temCe = (5/9)*(temFa-32)
  print(f"La Temperatura en Grados Celsius es: {temCe:.2}")

if opcion == "3":
  metros = float(input("Medida en Metros:"))
  centimetros = (metros)*(100)
  print(f"La medida en centímetros es: {centimetros:.2}")

if opcion == "4":
  centimetros = float(input("Medida en Centímetros:"))
  metros = (centimetros)/(100)
  print(f"La medida en metros es: {metros:.3}")

if opcion == "5":
  gramos = float(input("Masa en gramos:"))
  kilogramos = (gramos)/(1000)
  print(f"La Masa en kilogramos es: {kilogramos:.2}")

if opcion == "6":
  kilogramos = float(input("Masa en kilogramos:"))
  gramos = (kilogramos)*(1000)
  print(f"La Masa en gramos es: {gramos:.2}")

if opcion == "7":
  print("Fin de la ejecución")