# -*- coding: utf-8 -*-
"""CotizadorTienda.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_hLYyOgU0YHGEu_7lvuUuX9F4VsShamA
"""

print("-----Bienvenido a la calculadora de Cotizador de Producto-------")
print("Menu de Opciones")
print("1.- Precio del producto + IVA")
print("2.- Precio del producto con descuento + IVA")
print("3.- Costo total a Pagar")
print("4.- Salir")

opcion = input("Opción (1-4):")

if opcion == "1":
  precio = float(input("Escribe el Precio del Producto ($):"))
  premasiva = precio + (precio*0.16)
  print(f"El precio con IVA del 16 % es: {premasiva:.2}")

if opcion == "2":
  precio = float(input("Escribe el Precio del Producto ($):"))
  descuento = float(input("Escribe el Descuento (%):"))
  preciototal = precio + (precio*0.16)- ((descuento/100)*precio)
  print(f"El precio total con IVA del 16 % y con el descuento es: {preciototal:.2}")

if opcion == "3":
  precio = float(input("Escribe el Precio del Producto ($):"))
  descuento = float(input("Escribe el Descuento (%):"))
  cantidad = float(input("Escribe la Cantidad de Productos:"))
  preciototal = (precio + (precio*0.16)- ((descuento/100)*precio))*cantidad
  print(f"El costo a pagar por tus productos con IVA y con descuento es: {preciototal:.2}")

if opcion == "4":
  print("Vuelva Pronto")