# -*- coding: utf-8 -*-
"""GestorDeCalificaciones.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ArpD-QqH5dAlcCHfaz7KZfSyejUYvBJK
"""

print("-----Bienvenido a la calculadora de Gestor de Calificaciones-------")
print("Menu de Opciones")
print("1.- Calcular Promedio")
print("2.- Calcular calificación final")
print("3.- Tu Mayor y Menor calificación")
print("4.- Aprobado/Reprobado")
print("5.- Salir")

opcion = input("Opción (1-5):")

if opcion == "1":
  cal1 = float(input("Calificación (primer examen)):"))
  cal2 = float(input("Calificación (segundo examen)):"))
  cal3 = float(input("Calificación (tercer examen)):"))
  promedio = (cal1+cal2+cal3)/3
  print(f"Tu promedio de calificación es: {promedio:.2}")

if opcion == "2":
  cal1 = float(input("Calificación (primer examen)):"))
  cal2 = float(input("Calificación (segundo examen)):"))
  cal3 = float(input("Calificación (tercer examen)):"))
  promedio = (cal1+cal2+cal3)/3
  print(f"Tu calificación final es: {promedio:.2}")

if opcion == "3":
  cal1 = float(input("Calificación (primer examen):"))
  cal2 = float(input("Calificación (segundo examen):"))
  cal3 = float(input("Calificación (tercer examen):"))
  calificaciones = {cal1,cal2,cal3}
  mayorcalif = max(calificaciones)
  menorcalif = min(calificaciones)
  print(f"Tu calificación máxima es: {mayorcalif}")
  print(f"Tu calificación mínima es: {menorcalif}")

if opcion == "4":
  cal1 = float(input("Calificación (primer examen)):"))
  cal2 = float(input("Calificación (segundo examen)):"))
  cal3 = float(input("Calificación (tercer examen)):"))
  promedio = (cal1+cal2+cal3)/3
  print(f"Tu promedio de calificación es: {promedio:.2}")
  if promedio < 5:
    print("Reprobado")
  else:
   print("Aprobado")

if opcion == "5":
   print("Salir")